FROM python:3.6.7-stretch

ENV PYTHONUNBUFFERED 1

RUN apt-get update -y && apt-get install unixodbc unixodbc-dev -y

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements
RUN pip install --no-cache-dir -r /requirements/production.txt \
    && rm -rf /requirements

WORKDIR /app
