# Generated by Django 2.0.9 on 2018-11-03 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('referencia', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'beacons',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=45)),
                ('documento', models.CharField(max_length=45, null=True)),
                ('tipoDocumento', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('descuento', models.FloatField(default=0.0)),
                ('medioPago', models.IntegerField()),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='domain.Cliente')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('Materializado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='domain.Cliente')),
            ],
            options={
                'verbose_name_plural': 'beacons',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('beacon', models.ForeignKey(db_column='idBeacon', on_delete=django.db.models.deletion.CASCADE, to='domain.Beacon')),
            ],
            options={
                'verbose_name_plural': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('referencia', models.CharField(max_length=45)),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'product_types',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoProducto',
            field=models.ForeignKey(db_column='idTipoProducto', on_delete=django.db.models.deletion.CASCADE, to='domain.TipoProducto'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='domain.Producto'),
        ),
        migrations.AddField(
            model_name='interaccion',
            name='notificacion',
            field=models.ForeignKey(db_column='idNotificacion', on_delete=django.db.models.deletion.CASCADE, to='domain.Notificacion'),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(db_column='idProducto', on_delete=django.db.models.deletion.CASCADE, to='domain.Producto'),
        ),
    ]
